mysite/urls.py
from django.contrib import admin
from django.urls import path , include


urlpatterns = [
    path('uni/', include('uni.urls')),
    # path('login/page/',views.PageView.as_view(),name = 'page')
    path('admin/', admin.site.urls),
]

uni/mysite/urls.py
from django.contrib import admin
from django.urls import path , include


urlpatterns = [
    path('uni/', include('uni.urls')),
    # path('login/page/',views.PageView.as_view(),name = 'page')
    path('admin/', admin.site.urls),
]

uni/urls.py
from django.urls import path

from . import views


app_name = 'uni'
urlpatterns = [
    
    path('/fa', views.HomeView.as_view(), name='home'), #home page
    path('', views.Home_enView.as_view(), name='home_en'), 
    path('aboutus/<str:lang>', views.AboutusView.as_view(), name='aboutus'), 
    path('logout/', views.page_logout, name='logout'),
    path('login/<str:lang>',views.LoginView.as_view(),name = 'login'), #login page
    path('login/<str:lang>/forget',views.ForgetpassView.as_view(),name = 'forget'), 
    path('login/forget/<str:message>/<str:lang>/messagef',views.MessageboxfView.as_view(),name = 'messagef'), 
    path('student/<int:student_id>/page/',views.PageView.as_view(),name = 'page'),#student page
    path('Leader/<int:leader_id>/leader/',views.LeaderView.as_view(),name = 'leader'),
    path('Leader/<int:leader_id>/leader/createboss',views.CreatebossView.as_view(),name = 'createboss'),
    path('Boss/<int:boss_id>/boss/createadmin',views.CreateadminView.as_view(),name = 'createadmin'),
    path('Boss/<int:boss_id>/boss/',views.BossView.as_view(),name = 'boss'),
    path('Boss/<int:boss_id>/boss/changepassbs',views.ChangePassbsView.as_view(),name = 'changepassbs'),
    path('Leader/<int:leader_id>/leader/changepassled',views.ChangePassledView.as_view(),name = 'changepassled'),
    path('Boss/<int:boss_id>/boss/studentsbs',views.StudentsbsView.as_view(),name = 'studentsbs'),
    path('Boss/<int:boss_id>/boss/adminsbs',views.AdminsbsView.as_view(),name = 'adminsbs'),
    path('Boss/<int:boss_id>/boss/adminsbs/<int:admin_id>/adminbs',views.AdminbsView.as_view(),name = 'adminbs'),
    path('Boss/<int:boss_id>/boss/adminsbs/<int:admin_id>/adminbs/vahedbs2',views.Vahedbs2View.as_view(),name = 'vahedbs2'),
    path('Boss/<int:boss_id>/boss/studentsbs/<int:student_id>/studentbs',views.StudentbsView.as_view(),name = 'studentbs'),
    path('student/<int:student_id>/page/darkhast4',views.Darkhast4View.as_view(),name = 'darkhast4'),
    path('student/<int:student_id>/page/karname',views.KarnameView.as_view(),name = 'karname'),
    path('student/<int:student_id>/page/karname/<int:vahed_id>/eteraz',views.EterazView.as_view(),name = 'eteraz'),
    path('student/<int:student_id>/<str:message>/messages',views.MessageboxsView.as_view(),name = 'messages'),
    path('admin/<int:admin_id>/<str:message>/messagea',views.MessageboxaView.as_view(),name = 'messagea'),
    path('ostad/<int:ostad_id>/<str:message>/messageos',views.MessageboxosView.as_view(),name = 'messageos'),
    path('ostad/<int:leader_id>/<str:message>/messageled',views.MessageboxledView.as_view(),name = 'messageled'),
    path('ostad/<int:boss_id>/<str:message>/messagebs',views.MessageboxbsView.as_view(),name = 'messagebs'),
    path('student/<int:student_id>/page/karname/<int:vahed_id>/eteraz2',views.Eteraz2View.as_view(),name = 'eteraz2'),
    path('student/<int:student_id>/page/mydars',views.MydarsView.as_view(),name = 'mydars'),
    path('student/<int:student_id>/page/mydars/<int:vahed_id>/darkhast',views.DarkhastView.as_view(),name = 'darkhast'),
    path('student/<int:student_id>/page/entekhab',views.EntekhabView.as_view(),name = 'entekhab'),
    path('student/<int:student_id>/page/entekhab2',views.Entekhab2View.as_view(),name = 'entekhab2'),
    path('student/<int:student_id>/page/entekhab2/<int:vahed_id>/entekhab3',views.Entekhab3View.as_view(),name = 'entekhab3'),
    path('student/<int:student_id>/page/about',views.AboutSView.as_view(),name = 'aboutS'),#student's information page
    path('Boss/<int:boss_id>/boss/studentsbs/<int:student_id>/studentbs/aboutsbs',views.AboutSbsView.as_view(),name = 'aboutSbs'),
    path('Boss/<int:boss_id>/boss/studentsbs/<int:student_id>/studentbs/vahedbs',views.VahedbsView.as_view(),name = 'vahedbs'),
    path('Boss/<int:boss_id>/boss/studentsbs/<int:student_id>/studentbs/karnamebs',views.KarnamebsView.as_view(),name = 'karnamebs'),
    path('admin/<int:admin_id>/page2/',views.Page2View.as_view(),name = 'page2'),#admin's page
    path('admin/<int:admin_id>/page2/forget2',views.Forgetpass2View.as_view(),name = 'forget2'),
    path('admin/<int:admin_id>/page2/forget2/<int:ostad_id>/forget3',views.Forgetpass3View.as_view(),name = 'forget3'),
    path('admin/<int:admin_id>/page2/ejaze',views.EjazeView.as_view(),name = 'ejaze'),
    path('admin/<int:admin_id>/page2/darkhast2',views.Darkhast2View.as_view(),name = 'darkhast2'),
    path('admin/<int:admin_id>/page2/darkhast2/<int:darkhast_id>/darkhast3',views.Darkhast3View.as_view(),name = 'darkhast3'),
    path('admin/<int:admin_id>/page2/create',views.CreateView.as_view(),name = 'create'),#creat student page
    path('student/<int:student_id>/page/change',views.ChangeView.as_view(),name = 'change'),#change information page by student
    path('student/<int:student_id>/page/changepass',views.ChangePassView.as_view(),name = 'changepass'),# change password in student
    path('admin/<int:admin_id>/page2/changepass2',views.ChangePassView2.as_view(),name = 'changepass2'),# change password in admin
    path('admin/<int:admin_id>/page2/students',views.StudentsView.as_view(),name = 'students'),#students list in admin page
    path('admin/<int:admin_id>/page2/students/<int:student_id>',views.Student1View.as_view(),name = 'student1'),#student profile in admin
    path('admin/<int:admin_id>/page2/students/<int:student_id>/karname2',views.Karname2View.as_view(),name = 'karname2'),
    path('admin/<int:admin_id>/page2/students/<int:student_id>/vahed2',views.Vahed2View.as_view(),name = 'vahed2'),
    path('admin/<int:admin_id>/page2/students/<int:student_id>/about2',views.AboutS2View.as_view(),name = 'aboutS2'),#student info in admin
    path('admin/<int:admin_id>/page2/students/<int:student_id>/about2/change2',views.Change2View.as_view(),name = 'change2'),#change  passwprd in admin
    path('admin/<int:admin_id>/page2/students/<int:student_id>/about2/changepass3',views.ChangePassView3.as_view(),name = 'changepass3'),#change student passwprd by admin
    path('student/<int:student_id>/page/students2',views.StudentsView2.as_view(),name = 'students2'),#student list in student
    path('student/<int:student_id>/page/students2/<int:student2_id>',views.Student2View.as_view(),name = 'student2'),#student profile in student
    path('ostad/<int:ostad_id>/page3/',views.Page3View.as_view(),name = 'page3'),#ostad page
    path('ostad/<int:ostad_id>/page3/eteraz3',views.Eteraz3View.as_view(),name = 'eteraz3'),
    path('ostad/<int:ostad_id>/page3/eteraz3/<int:eteraz_id>/eteraz4',views.Eteraz4View.as_view(),name = 'eteraz4'),
    path('ostad/<int:ostad_id>/page3/eteraz3/<int:eteraz_id>/eteraz4/eteraz5',views.Eteraz5View.as_view(),name = 'eteraz5'),
    path('ostad/<int:ostad_id>/page3/mydars2',views.Mydars2View.as_view(),name = 'mydars2'),#ostad page
    path('ostad/<int:ostad_id>/page3/mydars2/<int:vahed_id>/nomre',views.NomreView.as_view(),name = 'nomre'),#ostad page
    path('ostad/<int:ostad_id>/page3/changepass4',views.ChangePassView4.as_view(),name = 'changepass4'),# change password in ostad
    path('ostad/<int:ostad_id>/page3/students3',views.Students3View.as_view(),name = 'students3'),#students list in ostad page
    path('ostad/<int:ostad_id>/page3/students3/<int:student_id>',views.Student3View.as_view(),name = 'student3'),#student profile in ostad
    path('ostad/<int:ostad_id>/page3/students3/<int:student_id>/about3',views.AboutS3View.as_view(),name = 'aboutS3'),#student info in ostad
    path('ostad/<int:ostad_id>/page3/elam1',views.ElamView1.as_view(),name = 'elam1'),
    path('ostad/<int:ostad_id>/page3/elam1/<str:el>/elam2',views.ElamView2.as_view(),name = 'elam2'),
    path('admin/<int:admin_id>/page2/create2',views.CreateView2.as_view(),name = 'create2'),#creat ostad page
    
    path('admin/<int:admin_id>/page2/barname1',views.BarnameView1.as_view(),name = 'barname1'),
    path('admin/<int:admin_id>/page2/barname3',views.BarnameView3.as_view(),name = 'barname3'),
    path('admin/<int:admin_id>/page2/barname1/barname2/<int:elam_id>',views.BarnameView2.as_view(),name = 'barname2'),
    path('admin/<int:admin_id>/page2/barname3/barname4/<int:elam_id>',views.BarnameView4.as_view(),name = 'barname4'),
    path('admin/<int:admin_id>/page2/barname1/barname2/<int:elam_id>/erae',views.EraeView.as_view(),name = 'erae'),
    path('admin/<int:admin_id>/page2/barname1/barname2/<int:elam_id>/erae/<int:klas_id>/erae2',views.Erae2View.as_view(),name = 'erae2'),
    path('admin/<int:admin_id>/page2/createklass',views.CreateklassView.as_view(),name = 'createklass'),
    path('admin/<int:admin_id>/page2/barname1/barname2/<int:elam_id>/erae/nahaee',views.NahaeeView.as_view(),name = 'nahaee'),
    path('admin/<int:admin_id>/page2/vahed',views.VahedView.as_view(),name = 'vahed'),
    path('ostad/<int:ostad_id>/page3/vaziat',views.VaziatView.as_view(),name = 'vaziat'),
    path('ostad/<int:ostad_id>/page3/vaziat/<int:elam_id>/vaziat2',views.Vaziat2View.as_view(),name = 'vaziat2'),
    path('ostad/<int:ostad_id>/page3/vaziat/<int:elam_id>/vaziat2/vaziat3',views.Vaziat3View.as_view(),name = 'vaziat3'),
    path('ostad/<int:ostad_id>/page3/vaziat/<int:elam_id>/vaziat2/vaziat3/vaziat4',views.Vaziat4View.as_view(),name = 'vaziat4'),
    # path('ostad/<int:ostad_id>/page3/vaziat/<int:elam_id>/vaziat5',views.Vaziat5View.as_view(),name = 'vaziat5'),
    



]

uni/templates/uni/aboutS_en.html
{% load static %}
<link rel="icon" href="{% static 'uni/images/13.png' %}">
<!DOCTYPE html>
<html>
    

<head>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
  table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: right;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<!DOCTYPE html>
<html>
    

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'uni/style2.css' %}">
</head>
<body style="text-align: right;">

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <ul>
      <li><a href="{% url 'uni:page' student.id %}">Home</a></li>
            
            <li><a href="{% url 'uni:aboutS' student.id %}">Student Informations</a></li>
            <li><a href="{% url 'uni:students2' student.id %}">Students</a></li>
            <li><a href=" {% url 'uni:entekhab' student.id %} ">Available Courses</a></li>
            <li><a href=" {% url 'uni:entekhab2' student.id %} ">Unit Selection</a></li>
            <li><a href=" {% url 'uni:mydars' student.id %} ">My Courses</a></li>
            <li><a href=" {% url 'uni:karname' student.id %} ">Show Report Card</a></li>
            <li><a href=" {% url 'uni:darkhast4' student.id %} ">My Requests</a></li>
            
            <li><a href="{% url 'uni:changepass' student.id %}">Change Password</a></li>
           
            <a  onClick="document.getElementById('logoutform').submit()" ><button class="cancelbtn"  style=" height: 54px;" type="button">Exit</button></a>
    </ul>
  </div>

  <link rel="stylesheet" type="text/css" href="{% static 'uni/style2.css' %}">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <div class="w3-container w3-dark-grey">
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <h2 style="text-align: left;" >{{ student.name  }} {{  student.last_name  }}</h2> 
  </div>
  <form id = "dem"class="modal-content animate" method="post" style="width: 1300px;">{% csrf_token %}
    <div class="imgcontainer">
      <a href="{% url 'uni:page' student.id %}"><span class="close" title="Close Modal">&times;</span></a>
      <br>
    </div>
    
    <div style="text-align: left;" class="container">
      <!-- <label for="uname"><b>Username</b></label> -->
      <!-- <input id = "usernamee" type="text" placeholder="Enter Username" name="uname" value="awmxr"> -->
      
      <table>
        <tr>
          <th style="text-align: center;"> Entering Year </th>
          <th style="text-align: center;"> Field of Study </th>
          <th style="text-align: center;">Phone Number </th>
          <th style="text-align: center;"> College </th>
          <th style="text-align: center;"> University </th>
          <th style="text-align: center;"> National ID </th>
          <th style="text-align: center;"> Student ID </th>
          <th style="text-align: center;"> Father's Name </th>
          <th style="text-align: center;">Name </th>
        </tr>
        <tr>
          <th style="text-align: center;"> {{ student.enter_year }} </th>
          <th style="text-align: center;"> {{ field }} </th>
          <th style="text-align: center;">{{ student.phone }}</th>
          <th style="text-align: center;"> {{ college }} </th>
          <th style="text-align: center;"> {{ uni }} </th>
          <th style="text-align: center;">  {{ student.melli_code }}</th>
          <th style="text-align: center;"> {{ student.username }} </th>
          <th style="text-align: center;"> {{ student.father_name }}</th>
          <th style="text-align: center;"> {{ student.name  }} {{ student.last_name  }}</th>
        </tr>
      </table>
      

      <!-- <label for="psw"><b>Password</b></label> -->
      <!-- <input type="password" placeholder="Enter Password" name="psw" required> -->
        
     <a href="{% url 'uni:change' student.id %}"> <button style="background-color: #b30e0e; font-size: large;" type="button">Edit</button></a>
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <div style="text-align: right;">
       <a href="{% url 'uni:page' student.id %}"> <button type="button" style="text-align: left;" class="cancelbtn">Cancel</button></a>
      </div>
    </div>

  </form>


<script>
// Get the modal
username = document.getElementsById("usernamee").value
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

</body>

<form id="logoutform" method="POST" action="{% url 'uni:logout' %}">
  {% csrf_token %}
  <input type="hidden">
  </form>
</html>

uni/templates/uni/forget2_en.html
{% load static %}
<link rel="icon" href="{% static 'uni/images/13.png' %}">
<!DOCTYPE html>
<html>
    

<head>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
  table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: right;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'uni/style2.css' %}">
</head>
<body style="text-align: right;">

    
    <ul>
      <li><a href="{% url 'uni:page2' admin.id %}">Home</a></li>
            <li><a href="{% url 'uni:students' admin.id %}">Students</a></li>
            <li><a href="{% url 'uni:create' admin.id %}">New Student</a></li>
            <li><a href="{% url 'uni:create2' admin.id %}">New Professor</a></li>
            <li><a href="{% url 'uni:barname1' admin.id  %}">Professors' Schedule</a></li>
            <li><a href="{% url 'uni:barname3' admin.id  %}">Rejected Schedule</a></li>
            <li><a href="{% url 'uni:vahed' admin.id  %}">Available Courses</a></li>
            <li><a href="{% url 'uni:ejaze' admin.id  %}">Unit Selection Permission</a></li>
            <li><a href="{% url 'uni:darkhast2' admin.id  %}">Course Delete Requests</a></li>
            <li><a href="{% url 'uni:createklass' admin.id %}">Add Class</a></li>
            <li><a href="{% url 'uni:changepass2' admin.id %}">Change Password</a></li>
            
            <a  onClick="document.getElementById('logoutform').submit()" ><button class="cancelbtn"  style=" height: 54px;" type="button">Exit</button></a>
    </ul>




    <div class="w3-container w3-dark-grey">        
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <h2 style="text-align: left; " >{{ admin.name  }} {{  admin.last_name  }}</h2> 
  </div>
    
  <form  id = "dem"class="modal-content animate" method="post" style="width: 1300px;">{% csrf_token %}
    <div class="imgcontainer">
      <a href=" {% url 'uni:page2' admin.id %} "><span  class="close" title="Close Modal">&times;</span></a>
      <br>
      <br>
    </div>
    
    <div style="text-align: left;" class="container">
      <!-- <label for="uname"><b>Username</b></label> -->
      <!-- <input id = "usernamee" type="text" placeholder="Enter Username" name="uname" value="awmxr"> -->
      <table>
        <tr>
            <th style="text-align: center;">Review</th>
          <th style="text-align: center;">Status</th>
          
          <th style="text-align: center;">Date of Request Submission</th>
          <th style="text-align: center;">Username</th>
          <th style="text-align: center;">Role</th>
          <th style="text-align: center;">Name</th>
        </tr>
        {% for i in forgets %}

        <tr>
            {% if not i.1.check and i.1.s%}
            <th style="text-align: center;"><a href="{% url 'uni:changepass3' admin.id i.0.id %}">Review</a> </th>
            {% elif not i.1.check and i.1.os%}
            <th style="text-align: center;"><a href="{% url 'uni:forget3' admin.id i.0.id %}">Review</a> </th>
            {% elif i.1.check %}
            <th style="text-align: center;">Reviewed</th>
            {% endif %}
          <th style="text-align: center;">{{i.2}}</th>
          
            <th style="text-align: center;">{{i.1.public_date}}</th>
            <th style="text-align: center;">{{i.0.username}}</th>
            {% if i.1.s %}
            <th style="text-align: center;">Student</th>
            {% elif i.1.os %}
            <th style="text-align: center;">Professor</th>
            {% endif %}
            <th style="text-align: center;">{{i.0.name}} {{i.0.last_name}}</th>
            
          </tr>




        {% endfor %}
        

      </table>
      
      
      {% if error_message %}<p style="color: red;">{{ error_message }}</p>{% endif %}
      
      

      <!-- <label for="psw"><b>Password</b></label> -->
      <!-- <input type="password" placeholder="Enter Password" name="psw" required> -->
        
      
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <div style="text-align: right;">
        <a href="{% url 'uni:page2' admin.id %}"><button type="button" style="text-align: left;"  class="cancelbtn">Cancel</button></a>
        
      </div>
    </div>

  </form>


<script>
// Get the modal
username = document.getElementsById("usernamee").value
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>


</body>

<form id="logoutform" method="POST" action="{% url 'uni:logout' %}">
  {% csrf_token %}
  <input type="hidden">
  </form>
</html>

uni/templates/uni/home.html
{% load static %}


<link rel="icon" href="{% static 'uni/images/13.png' %}">
<link rel="stylesheet" type="text/css" href="{% static 'uni/style.css' %}">
<body>


<!-- charset=utf-8 -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<ul>
  <li><a href="{% url 'uni:home' %}">خانه</a></li>
  <li><a href="{% url 'uni:login' lang %}">ورود</a></li>
  
  <li><a href="{% url 'uni:aboutus' lang %}">درباره ما</a></li>
  <form method ="POST" >
    {% csrf_token %}
  <select   onchange="this.form.submit()"   name='lang'  style="height: 40px;width: 100px; background-color: rgb(39, 37, 37); border-color: rgb(39, 37, 37); color:aliceblue">
    <option value="en">English</option>
    <option value="fa" selected>فارسی</option>
    
    
  </select>
</form>

</ul>
{{name}}
{% if messages %}
        <ul style="color: aliceblue ;background-color: rgb(8, 148, 78);" class="messages">
            {% for message in messages %}
            <h2>  <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>  {{ message }}</li></h2>
            {% endfor %}
        </ul>
{% endif %}



</body>

<form id="logoutform" method="POST" action="{% url 'uni:logout' %}">
  {% csrf_token %}
  <input type="hidden">
  </form>

uni/templates/uni/nahaee.html
{% load static %}
<link rel="icon" href="{% static 'uni/images/13.png' %}">
<!DOCTYPE html>
<html>
    

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'uni/style2.css' %}">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
    table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>

<body style="text-align: left;">

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <ul>
      <li><a href="{% url 'uni:page2' admin.id %}">خانه</a></li>
      <li><a href="{% url 'uni:students' admin.id %}">دانشجویان</a></li>
      <li><a href="{% url 'uni:create' admin.id %}">دانشجوی جدید</a></li>
      <li><a href="{% url 'uni:create2' admin.id %}">استاد جدید</a></li>
      <li><a href="{% url 'uni:barname1' admin.id  %}">برنامه استادان</a></li>
      <li><a href="{% url 'uni:barname3' admin.id  %}">برنامه های رد شده</a></li>
      <li><a href="{% url 'uni:vahed' admin.id  %}">واحد های ارعه شده</a></li>
      <li><a href="{% url 'uni:ejaze' admin.id  %}">اجازه انتخاب واحد</a></li>
      <li><a href="{% url 'uni:darkhast2' admin.id  %}">درخواست های حذف</a></li>
      <li><a href="{% url 'uni:createklass' admin.id %}">ثبت کلاس</a></li>
      <li><a href="{% url 'uni:changepass2' admin.id %}">تغیر رمز عبور</a></li>
      
      <a  onClick="document.getElementById('logoutform').submit()" ><button class="cancelbtn"  style=" height: 54px;" type="button">خروج</button></a>
        
    </ul>
  </div>

  <link rel="stylesheet" type="text/css" href="{% static 'uni/style2.css' %}">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <div class="w3-container w3-dark-grey">
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <h2 style="text-align: right;" >{{ admin.name  }} {{  admin.last_name  }}</h2> 
  </div>
  <form id = "dem"class="modal-content animate" method="post" style="width: 1300px;">{% csrf_token %}
    <div class="imgcontainer">
      <a href="{% url 'uni:page2' admin.id %}"><span class="close" title="Close Modal">&times;</span></a>
      <br>
    </div>
    
    <div style="text-align: right;" class="container">
      <!-- <label for="uname"><b>Username</b></label> -->
      <!-- <input id = "usernamee" type="text" placeholder="Enter Username" name="uname" value="awmxr"> -->
      
  




        <table>
          <tr>
            <th style="text-align: center;">گروه</th>
            <th style="text-align: center;">استاد مربوطه</th>
            <th style="text-align: center;">ظرفیت</th>
            <th style="text-align: center;">جنسیت</th>
            <th style="text-align: center;">واحد</th>
            <th style="text-align: center;">کد درس</th>
            <th style="text-align: center;">درس</th>
          </tr>
          <tr>
            <th style="text-align: center;">{{elam.goruh}}</th>
            <th style="text-align: center;">{{ os.name  }} {{os.last_name}}</th>
            <th style="text-align: center;">{{elam.capacity}}</th>
            <th style="text-align: center;">{{sex}}</th>
            <th style="text-align: center;">{{elam.vahed}}</th>
            <th style="text-align: center;">{{exter.code}}</th>
            <th style="text-align: center;">{{dars}}</th>
          </tr>
        </table>



        <br>
        <br>
        <h3 >تاریخ و ساعت امتحان</h3>
        <input type="datetime-local" name="exam">
        <h2>روز های انتخابی</h2>
        <table >
            
            {% for i in list1 %}
            <tr>
              <th ><h3 style="text-align: center;">{{ i }}</h3></th>
            </tr>
            {% endfor %}
        </table>
        <div>
            <button name = 'erae' value='yes' style="background-color: #06af22; font-size: large;" type="submit"> تایید نهایی</button>
        </div>
        
        
        
   
      
   {% if error_message %}<p style="color: red;">{{ error_message }}</p>{% endif %}
      <!-- <label for="psw"><b>Password</b></label> -->
      <!-- <input type="password" placeholder="Enter Password" name="psw" required> -->
        
     
    </div>
    
    <div class="container" style="background-color:#f1f1f1">
      <div style="text-align: left;">
       <a href="{% url 'uni:page2' admin.id  %}"> <button type="submit" name = 'erae' value="no" style="text-align: right;" class="cancelbtn">لغو</button></a>
      </div>
    </div>

  </form>


<script>
// Get the modal
username = document.getElementsById("usernamee").value
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

</body>

<form id="logoutform" method="POST" action="{% url 'uni:logout' %}">
  {% csrf_token %}
  <input type="hidden">
  </form>
</html>